# Generated by Django 3.2.16 on 2023-04-19 15:20

from django.db import migrations


def create_customer_code_types(apps, schema_editor):
    CustomerCodeType = apps.get_model("sales", "CustomerCodeType")
    types = [
        ("04", "RUC", 13),
        ("05", "CÉDULA", 10),
        ("06", "PASAPORTE", 99),
        ("07", "VENTA A CONSUMIDOR FINAL", 13),
        ("08", "IDENTIFICACIÓN DEL EXTERIOR", 99),
    ]
    code_types = [
        CustomerCodeType(code=code, name=name, length=long)
        for code, name, long in types
    ]
    CustomerCodeType.objects.bulk_create(code_types)


def create_final_consumer_customer(apps, schema_editor):
    CustomerCodeType = apps.get_model("sales", "CustomerCodeType")
    Customer = apps.get_model("sales", "Customer")
    Customer.objects.create(
        code_type=CustomerCodeType.objects.get(code="07"),
        code="9999999999999",
        bussiness_name="CONSUMIDOR FINAL",
        email="consumidor.final@test.com",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=create_customer_code_types, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            code=create_final_consumer_customer, reverse_code=migrations.RunPython.noop
        ),
    ]
