# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0007_auto_20171022_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('ruc', models.CharField(max_length=16)),
                ('telephone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('untaxed_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='impuestos')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'Ventas'), (2, 'Compras'), (3, 'Ninguno')])),
                ('amount_type', models.PositiveSmallIntegerField(choices=[(1, 'Fijo'), (2, 'Porcentaje sobre el precio')])),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='taxes',
            field=models.ManyToManyField(to='billing.Tax'),
        ),
    ]
