# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100, verbose_name='direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=140, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ruc',
            field=models.CharField(max_length=16, verbose_name='ruc'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(max_length=10, verbose_name='tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='amount',
            field=models.FloatField(verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='amount_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fijo'), (2, 'Porcentaje sobre el precio')], verbose_name='tipo de c\xe1lculo'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=140, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='scope',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ventas'), (2, 'Compras'), (3, 'Ninguno')], verbose_name='\xe1mbito'),
        ),
    ]
