# Generated by Django 3.2.16 on 2023-03-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("cht", "charter"),
                            ("ruc", "ruc"),
                            ("pst", "passport"),
                            ("fgn", "foreign identification"),
                        ],
                        max_length=4,
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("first_name", models.CharField(blank=True, max_length=64, null=True)),
                ("last_name", models.CharField(blank=True, max_length=64, null=True)),
                ("bussiness_name", models.CharField(max_length=128)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=16, null=True)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
