version: "3.8"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: faclab
    container_name: web
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - faclab_net
  db:
    image: postgres:14
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - faclab_net
  redis:
    restart: unless-stopped
    image: redis
    container_name: cache
    expose:
      - "6379"
    networks:
      - faclab_net
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - faclab_net

networks:
  faclab_net:
