# Generated by Django 3.2.16 on 2025-02-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sri_config", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("2", "IVA"), ("3", "ICE")],
                        default="2",
                        max_length=4,
                        verbose_name="type",
                    ),
                ),
                ("code", models.CharField(max_length=4, verbose_name="code")),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("fee", models.PositiveSmallIntegerField(verbose_name="fee")),
            ],
            options={
                "verbose_name": "tax",
                "verbose_name_plural": "taxes",
            },
        ),
    ]
