# Generated by Django 3.2.16 on 2024-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(max_length=64, verbose_name="subject"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="serial number"
                    ),
                ),
                ("issue_date", models.DateTimeField(verbose_name="issue date")),
                ("expiry_date", models.DateTimeField(verbose_name="expiry date")),
                ("cert", models.TextField()),
                ("key", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sri_config", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("iva", "value added tax")],
                        default="iva",
                        max_length=32,
                        verbose_name="type",
                    ),
                ),
                ("code", models.CharField(max_length=4, verbose_name="code")),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("fee", models.PositiveSmallIntegerField(verbose_name="fee")),
            ],
        ),
    ]
