# Generated by Django 3.2.16 on 2024-03-29 13:35

from django.db import migrations


def create_empty_config(apps, schema_editor):
    Site = apps.get_model("core", "Site")
    Site.objects.create(sri_config=dict())


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=create_empty_config, reverse_code=migrations.RunPython.noop
        )
    ]
