# Generated by Django 3.2.16 on 2024-05-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20240502_2139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tax",
            name="type",
            field=models.CharField(
                choices=[("2", "IVA"), ("3", "ICE")],
                default="2",
                max_length=4,
                verbose_name="type",
            ),
        ),
    ]
