# Generated by Django 3.2.16 on 2024-05-01 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, verbose_name="code")),
                ("name", models.CharField(max_length=64, verbose_name="name")),
            ],
            options={
                "verbose_name": "measure",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, verbose_name="code")),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "short_name",
                    models.CharField(max_length=16, verbose_name="short name"),
                ),
                ("description", models.TextField(verbose_name="description")),
                ("sku", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "is_inventoried",
                    models.BooleanField(default=True, verbose_name="is inventoried"),
                ),
                (
                    "apply_iva",
                    models.BooleanField(default=False, verbose_name="apply iva"),
                ),
                (
                    "apply_ice",
                    models.BooleanField(default=False, verbose_name="apply ice"),
                ),
                ("stock", models.FloatField(default=0, verbose_name="stock")),
                (
                    "warehouse_location",
                    models.TextField(
                        blank=True, null=True, verbose_name="warehouse location"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("p", "Producto"), ("s", "Servicio")],
                        max_length=2,
                        null=True,
                        verbose_name="type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("p", "purchase"), ("s", "sale")],
                        max_length=2,
                        verbose_name="type",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="amount")),
                ("revenue", models.FloatField(verbose_name="revenue")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="inventory.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="inventory.productcategory",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.productcategory",
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="measure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.measure",
                verbose_name="unit of measure",
            ),
        ),
    ]
