# Generated by Django 3.2.16 on 2025-02-20 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("core", "0001_initial"),
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchase.provider",
                verbose_name="provider",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="taxes",
            field=models.ManyToManyField(
                blank=True, to="core.Tax", verbose_name="taxes"
            ),
        ),
    ]
