# Generated by Django 3.2.16 on 2024-05-03 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "product"},
        ),
        migrations.CreateModel(
            name="StockMove",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("i", "initial inventory"),
                            ("p", "purchase"),
                            ("s", "sale"),
                        ],
                        max_length=4,
                        verbose_name="type",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="date")),
                ("entry", models.FloatField(default=0, verbose_name="entry")),
                ("outflow", models.FloatField(default=0, verbose_name="outflow")),
                ("stock", models.FloatField(default=0, verbose_name="stock")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock move",
                "verbose_name_plural": "stock moves",
            },
        ),
    ]
