# Generated by Django 3.2.16 on 2024-05-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_auto_20240502_1527"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("p", "Producto"), ("s", "Servicio")],
                default="p",
                max_length=2,
                verbose_name="type",
            ),
        ),
    ]
