# Generated by Django 3.2.16 on 2023-04-01 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, verbose_name="code")),
                ("name", models.CharField(max_length=64, verbose_name="name")),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="warehouses.productcategory",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, verbose_name="code")),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "short_name",
                    models.CharField(max_length=16, verbose_name="short name"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "is_inventoried",
                    models.BooleanField(default=True, verbose_name="is inventoried"),
                ),
                (
                    "apply_iva",
                    models.BooleanField(default=False, verbose_name="apply iva"),
                ),
                (
                    "apply_ice",
                    models.BooleanField(default=False, verbose_name="apply ice"),
                ),
                ("stock", models.FloatField(default=0, verbose_name="stock")),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("p", "Producto"), ("s", "Servicio")],
                        max_length=2,
                        null=True,
                        verbose_name="type",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouses.productcategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouses.measure",
                        verbose_name="unit of measure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("p", "purchase"), ("s", "sale")],
                        max_length=2,
                        verbose_name="type",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="amount")),
                ("revenue", models.FloatField(verbose_name="revenue")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="warehouses.product",
                    ),
                ),
            ],
        ),
    ]
